select distinct 
       IV.IMAGERY_PACKAGE_ID, 
       IV.CLASSIFICATION, 
       IV.IMAGERY_PACKAGE_NAME,
       IV.INSERTION_TIME_STAMP,
	   IV.FIRST_FRAME_FILEPATH,
       IV.CLIP_COUNT,
       IV.FRAME_COUNT,
       IFNULL(H.CLIP_HIT_COUNT, 0) as CLIP_HIT_COUNT,
       IFNULL(H.FRAME_HIT_COUNT, 0) as FRAME_HIT_COUNT
from IMAGERY_PACKAGE_SUMMARY_VIEW IV
left join 
	(select 
		F.IMAGERY_PACKAGE_ID, 
	 	count(distinctF.VIDEO_CLIP_GUID) as CLIP_HIT_COUNT,
	 	count(1) as FRAME_HIT_COUNT
	 from VIDEO_CLIP_FRAME F
	 inner join VIDEO V on V.IMAGERY_PACKAGE_ID = F.IMAGERY_PACKAGE_ID
	 where <FILTER EXPRESSIONS HERE>
	 group by F.IMAGERY_PACKAGE_ID) as H 
on H.IMAGERY_PACKAGE_ID = IV.IMAGERY_PACKAGE_ID
