CREATE COLUMN TABLE ANNOTATION_REQUEST
(
	ANNOTATION_PACKAGE_UUID VARCHAR(36) NOT NULL,
	IMAGERY_PACKAGE_UUID VARCHAR(36) NOT NULL,
	SEQUENCE_CLIP_UUID	VARCHAR(36) NOT NULL,
	SEQ_FRAME INTEGER,
	ANNOTATION_SOURCE VARCHAR(50) NOT NULL,
	ANALYSIS_TYPE VARCHAR(20) NOT NULL,
	USERNAME VARCHAR(40) NOT NULL,
	INSERTION_TIMESTAMP TIMESTAMP NOT NULL,
	STATUS		VARCHAR(30) NOT NULL,
	STATUS_TIMESTAMP TIMESTAMP NOT NULL,
	STATUS_MESSAGE VARCHAR(1000),
	ANNOTATION_FILE_PATH VARCHAR(200),
	PRIMARY KEY (ANNOTATION_PACKAGE_UUID)
) 