CREATE COLUMN TABLE IMAGERY_PACKAGE_DATA_CARD
(
	IMAGERY_PACKAGE_UUID VARCHAR(36) NOT NULL,
	CLASSIFICATION VARCHAR(20) NOT NULL,
	INSERTION_TIMESTAMP TIMESTAMP NOT NULL,
	BATCH_NAME VARCHAR(200) NOT NULL,
	IMAGERY_PACKAGE_TYPE VARCHAR(20) NOT NULL,
	IMAGERY_PACKAGE_NAME NVARCHAR(100),
	IMAGERY_PACKAGE_DESCRIPTION NVARCHAR(1000),
	IMAGERY_PACKAGE_GEO_AREA ST_GEOMETRY(1000004326),
	TE_DESIGNATION VARCHAR(20),
	PRIMARY KEY (IMAGERY_PACKAGE_UUID)
);