CREATE COLUMN TABLE SEQUENCE_FRAME_TAG
(
	SEQUENCE_FRAME_UUID VARCHAR(36) NOT NULL,
	INSERTION_TIME_STAMP TIMESTAMP NOT NULL,
	IMAGERY_PACKAGE_UUID VARCHAR(40) NOT NULL,
	TAG_USER VARCHAR(100) NOT NULL,
	TAG_TYPE VARCHAR(100) NOT NULL,
	TAG_VALUE VARCHAR(5000) NOT NULL,
	PRIMARY KEY (SEQUENCE_FRAME_UUID, INSERTION_TIME_STAMP)
);