CREATE COLUMN TABLE SEQUENCE_FRAME_FACE_ANNOTATION_ATTRIBUTE 
(
	ANNOTATION_UUID VARCHAR(36) NOT NULL,
	FACE_ATTRIBUTE_TYPE VARCHAR(20) NOT NULL,
	FACE_ATTRIBUTE_VALUE NVARCHAR(20) NOT NULL,
	CONFIDENCE INTEGER NOT NULL,
	PRIMARY KEY INVERTED INDIVIDUAL (ANNOTATION_UUID, FACE_ATTRIBUTE_TYPE, FACE_ATTRIBUTE_VALUE)
)