CREATE COLUMN TABLE SEQUENCE_CLIP_TAG
(
	SEQUENCE_CLIP_UUID VARCHAR(36) NOT NULL,
	INSERTION_TIME_STAMP TIMESTAMP NOT NULL,
	IMAGERY_PACKAGE_UUID VARCHAR(36) NOT NULL,
	TAG_USER VARCHAR(100) NOT NULL,
	TAG_TYPE VARCHAR(100) NOT NULL,
	TAG_VALUE VARCHAR(5000) NOT NULL,
	PRIMARY KEY (SEQUENCE_CLIP_UUID, INSERTION_TIME_STAMP)
);