CREATE COLUMN TABLE SEQUENCE_FRAME_TRACK_ANNOTATION_TAG
(
	ANNOTATION_UUID VARCHAR(36) NOT NULL,
	INSERTION_TIME_STAMP TIMESTAMP NOT NULL,
	TAG_USER VARCHAR(100) NOT NULL,
	TAG_TYPE VARCHAR(100) NOT NULL,
	TAG_VALUE VARCHAR(5000) NOT NULL,
	PRIMARY KEY INVERTED INDIVIDUAL 
	(
		ANNOTATION_UUID, INSERTION_TIME_STAMP
	)
);