CREATE COLUMN TABLE USER_MULTIPART_IMAGERY_DOWNLOAD
(
	DOWNLOAD_ID VARCHAR(40) not null,
	DOWNLOAD_GROUP_NAME VARCHAR(100) not null,
	PART_NUMBER INTEGER not null,
	TOTAL_PART_COUNT INTEGER not null,
	CREATE_TIME TIMESTAMP  not null,
	OBJECT_UUID VARCHAR(40) not null,
	OBJECT_TYPE VARCHAR(100) not null,
	USERNAME VARCHAR(32) not null,
	MESSAGE VARCHAR(512),
	DETAIL VARCHAR(512),
	DOWNLOAD_TIME TIMESTAMP,
	DOWNLOAD_DESCRIPTION VARCHAR(1000),
	PRIMARY KEY(DOWNLOAD_ID, PART_NUMBER)
)