CREATE COLUMN TABLE VIDEO 
(
	IMAGERY_PACKAGE_UUID VARCHAR(36) NOT NULL,
	CLASSIFICATION     VARCHAR(20) NOT NULL,
	DERIVATION_TYPE VARCHAR(50),
	ORIGIN_ID VARCHAR(100),
	SRC_RECORD_KEY BIGINT,
	CODEC_NAME VARCHAR(20),
	HEIGHT INTEGER,
	WIDTH INTEGER,
	PIX_FMT VARCHAR(20),
	BIT_RATE INTEGER,
	DURATION_SECONDS DOUBLE,
	BITS_PER_RAW_SAMPLE INTEGER,
	KLV_NAME VARCHAR(20),
	FRAME_COUNT INTEGER,
	STREAM_COUNT INTEGER,
	FORMAT_NAME VARCHAR(50),
	FPS DOUBLE,
	VIDEO_SIZE_BYTES BIGINT,
	INSERTION_TIMESTAMP TIMESTAMP,
	PRIMARY KEY (IMAGERY_PACKAGE_UUID)
);