CREATE COLUMN TABLE DATA_FILE
(
	"DATA_SET_ID" 		NVARCHAR(32),
	"DATA_FILE_ID" 		NVARCHAR(32),
	"FILE_NAME" 		VARCHAR(250),
	"CLASSIFICATION" 	VARCHAR(25),
	"DATA_SET_URL" 		VARCHAR(2000),
	"DATA_SET_PATH" 	VARCHAR(2000),
	"FILE_TYPE" 		VARCHAR(30),
	"FILE_SIZE_MB" 		DECIMAL(17,3),
	"NUMBER_ROWS" 		INTEGER ,
	"LAST_MOD_DATE" 	TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
) UNLOAD PRIORITY 5 AUTO MERGE 
	 