CREATE COLUMN TABLE DATA_SET
(
	"DATA_SET_ID" 		NVARCHAR(32),
	"DATA_CARD_ID" 		NVARCHAR(32),
	"HUMAN_ID" 			NVARCHAR(32),
	"NAME" 				NVARCHAR(250),
	"SOURCE" 			NVARCHAR(255),
	"DESCRIPTION" 		NVARCHAR(5000),
	"PRIME_CATEGORY" 	NVARCHAR(250),
	"SUB_CATEGORY" 		NVARCHAR(250),
	"ACCESS_TYPE" 		NVARCHAR(25),
	"LOAD_STATUS" 		NVARCHAR(25),
	"LOAD_FREQUENCY" 	NVARCHAR(25),
	"DATANODE_PATH" 	NVARCHAR(2000),
	"PATH" 				NVARCHAR(2000),
	"URL" 				NVARCHAR(2000),
	"CLASSIFICATION" 	NVARCHAR(50),
	"CONNECTION_ID" 	NVARCHAR(256),
	"DATA_CARD_STATUS" 	NVARCHAR(25),
	"COMMENTS" 			NVARCHAR(5000),
	"MODEL_INPUT" 		NVARCHAR(250),
	"MODEL_VENDORS" 	NVARCHAR(250),
	"LAST_MOD_DATE" 	TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL ,
	"LAST_MOD_BY" 		NVARCHAR(25)
) UNLOAD PRIORITY 5 AUTO MERGE 
	 
	 