CREATE VIEW GENERAL_SEARCH_VIEW
AS
select 
	'DATASET' as OBJECT_TYPE,
	D.CLASSIFICATION,
	D.DATA_SET_ID as OBJECT_ID,
	I.DATA_FILE_ID as CHILD_ID,
	I.TA_TOKEN as TOKEN,
	D.SOURCE,
	D.NAME,
	D.DESCRIPTION,
	D.LAST_MOD_DATE as OBJECT_TIMESTAMP,
	100 as CONFIDENCE
from "$TA_TEXT_EXT_CORE_INDEX" I
inner join DATA_FILE F on F.DATA_FILE_ID = I.DATA_FILE_ID
inner join DATA_SET D on D.DATA_SET_ID = F.DATA_SET_ID
UNION ALL
select 
	'DATASET' as OBJECT_TYPE,
	D.CLASSIFICATION,
	D.DATA_SET_ID as OBJECT_ID,
	I.DATA_FILE_ID as CHILD_ID,
	I.TA_TOKEN as TOKEN,
	D.SOURCE,
	D.NAME,
	D.DESCRIPTION,
	D.LAST_MOD_DATE as OBJECT_TIMESTAMP,
	100 as CONFIDENCE
from "$TA_BIN_EXT_CORE_INDEX" I
inner join DATA_FILE F on F.DATA_FILE_ID = I.DATA_FILE_ID
inner join DATA_SET D on D.DATA_SET_ID = F.DATA_SET_ID
UNION ALL
select 'IMAGERY' as OBJECT_TYPE,
	P.CLASSIFICATION,
    A.IMAGERY_PACKAGE_UUID as OBJECT_ID,
	F.SEQUENCE_CLIP_UUID as CHILD_ID,
	A.LABEL_NAME as TOKEN,
	P.IMAGERY_PACKAGE_TYPE as SOURCE,
	P.IMAGERY_PACKAGE_NAME as NAME,
	P.IMAGERY_PACKAGE_DESCRIPTION as DESCRIPTION,
	P.INSERTION_TIMESTAMP as OBJECT_TIMESTAMP,
	A.CONFIDENCE 
from SEQUENCE_FRAME_TRACK_ANNOTATION A
inner join SEQUENCE_FRAME F on F.SEQUENCE_FRAME_UUID = A.SEQUENCE_FRAME_UUID
inner join IMAGERY_PACKAGE_DATA_CARD P 
	on P.IMAGERY_PACKAGE_UUID = A.IMAGERY_PACKAGE_UUID
UNION ALL
select 'IMAGERY' as OBJECT_TYPE,
	P.CLASSIFICATION,
    C.IMAGERY_PACKAGE_UUID as OBJECT_ID,
	A.SEQUENCE_CLIP_UUID as CHILD_ID,
	A.LABEL as TOKEN,
	P.IMAGERY_PACKAGE_TYPE as SOURCE,
	P.IMAGERY_PACKAGE_NAME as NAME,
	P.IMAGERY_PACKAGE_DESCRIPTION as DESCRIPTION,
	P.INSERTION_TIMESTAMP as OBJECT_TIMESTAMP,
	A.CONFIDENCE
from SEQUENCE_CLIP_FRAME_LABEL A
inner join SEQUENCE_CLIP C on C.SEQUENCE_CLIP_UUID = A.SEQUENCE_CLIP_UUID
inner join IMAGERY_PACKAGE_DATA_CARD P 
	on P.IMAGERY_PACKAGE_UUID = C.IMAGERY_PACKAGE_UUID
UNION ALL
select 'IMAGERY' as OBJECT_TYPE,
	P.CLASSIFICATION,
    A.IMAGERY_PACKAGE_UUID as OBJECT_ID,
	A.SEQUENCE_CLIP_UUID as CHILD_ID,
	A.DETECTED_TEXT as TOKEN,
	P.IMAGERY_PACKAGE_TYPE as SOURCE,
	P.IMAGERY_PACKAGE_NAME as NAME,
	P.IMAGERY_PACKAGE_DESCRIPTION as DESCRIPTION,
	P.INSERTION_TIMESTAMP as OBJECT_TIMESTAMP,
	A.CONFIDENCE
from SEQUENCE_FRAME_TEXT_ANNOTATION A
inner join IMAGERY_PACKAGE_DATA_CARD P 
	on P.IMAGERY_PACKAGE_UUID = A.IMAGERY_PACKAGE_UUID
UNION ALL
select 'IMAGERY' as OBJECT_TYPE,
	P.CLASSIFICATION,
    A.IMAGERY_PACKAGE_UUID as OBJECT_ID,
	A.SEQUENCE_CLIP_UUID as CHILD_ID,
	AA.FACE_ATTRIBUTE_VALUE as TOKEN,
	P.IMAGERY_PACKAGE_TYPE as SOURCE,
	P.IMAGERY_PACKAGE_NAME as NAME,
	P.IMAGERY_PACKAGE_DESCRIPTION as DESCRIPTION,
	P.INSERTION_TIMESTAMP as OBJECT_TIMESTAMP,
	AA.CONFIDENCE
from SEQUENCE_FRAME_FACE_ANNOTATION A
inner join SEQUENCE_FRAME_FACE_ANNOTATION_ATTRIBUTE AA
	on AA.ANNOTATION_UUID = A.ANNOTATION_UUID
inner join IMAGERY_PACKAGE_DATA_CARD P 
	on P.IMAGERY_PACKAGE_UUID = A.IMAGERY_PACKAGE_UUID
	
 
	