CREATE VIEW IMAGERY_PACKAGE_SUMMARY_VIEW
as
select distinct 
	F.IMAGERY_PACKAGE_UUID,
    I.CLASSIFICATION, 
	I.IMAGERY_PACKAGE_TYPE,
    I.IMAGERY_PACKAGE_NAME,
	I.IMAGERY_PACKAGE_DESCRIPTION,
    I.INSERTION_TIMESTAMP,
	I.TE_DESIGNATION,
	min(F.ORIGINAL_TIMESTAMP) as IMAGERY_START_TIME_STAMP,
	max(F.ORIGINAL_TIMESTAMP) as IMAGERY_END_TIME_STAMP,	
	V.DURATION_SECONDS,
    FIRST_VALUE (F.FRAME_IMAGE_FILE_PATH order by F.SRC_VIDEO_FRAME) as FIRST_FRAME_FILEPATH,
	count(distinct F.SEQUENCE_CLIP_UUID) as CLIP_COUNT,
    count(1) as FRAME_COUNT
from SEQUENCE_FRAME_VIEW F
inner join IMAGERY_PACKAGE_DATA_CARD I on I.IMAGERY_PACKAGE_UUID = F.IMAGERY_PACKAGE_UUID 
inner join VIDEO V on I.IMAGERY_PACKAGE_UUID = V.IMAGERY_PACKAGE_UUID
group by
	F.IMAGERY_PACKAGE_UUID,
	 I.CLASSIFICATION,
	 I.IMAGERY_PACKAGE_TYPE,
	 I.IMAGERY_PACKAGE_NAME,
	 I.IMAGERY_PACKAGE_DESCRIPTION,
	 I.INSERTION_TIMESTAMP,
	 I.TE_DESIGNATION,
	 V.DURATION_SECONDS