CREATE VIEW SEQUENCE_CLIP_OBJECTS_VIEW
AS 
select distinct 
	CV.SEQUENCE_CLIP_UUID,
	CV.CLIP_NAME,
	CV.SEQUENCE_CLIP_FILE_PATH,
	CV.SEQUENCE_CLIP_FILENAME,
	A.OBJECT_ID,
	A.OBJECT_NAME,
	A.LABEL_NAME,
	count(1) as OBJECT_FRAME_COUNT 
from SEQUENCE_CLIP_VIEW CV 
inner join SEQUENCE_FRAME F on F.SEQUENCE_CLIP_UUID = CV.SEQUENCE_CLIP_UUID
inner join SEQUENCE_FRAME_TRACK_ANNOTATION A on A.SEQUENCE_FRAME_UUID = F.SEQUENCE_FRAME_UUID 
group by 
	CV.SEQUENCE_CLIP_UUID,
	CV.CLIP_NAME,
	CV.SEQUENCE_CLIP_FILE_PATH,
	CV.SEQUENCE_CLIP_FILENAME,
	A.OBJECT_ID,
	A.OBJECT_NAME,
	A.LABEL_NAME;