CREATE VIEW SEQUENCE_FRAME_OBJECTS_VIEW 
AS 
select  
	FV.SEQUENCE_CLIP_UUID,
	FV.SEQUENCE_FRAME_UUID,
	FV.SEQ_FRAME,
	CV.CLIP_NAME,
	CV.SEQUENCE_CLIP_FILE_PATH, 
	FV.FRAME_FILENAME,
	FV.FRAME_IMAGE_FILE_PATH,
	A.ANNOTATION_PACKAGE_UUID,
	A.ANNOTATION_UUID,
	A.OBJECT_NAME,
	A.LABEL_NAME,
	A.TRACK_ID,
	A.OBJECT_ID,
	A.ANNOTATION_TYPE,
	A.COORDS,
	A.ANNOTATION_GEO_POLYGON.ST_AsGeoJSON() as ANNOTATION_GEO_POLYGON_AS_GEOJSON 
from SEQUENCE_CLIP_VIEW CV 
inner join SEQUENCE_FRAME_VIEW FV on FV.SEQUENCE_CLIP_UUID = CV.SEQUENCE_CLIP_UUID 
inner join SEQUENCE_FRAME_TRACK_ANNOTATION A on A.SEQUENCE_FRAME_UUID = FV.SEQUENCE_FRAME_UUID 
