CREATE VIEW SEQUENCE_FRAME_VIEW 
AS 
SELECT
    F.*,
	C.CLIP_NAME || '-' || LPAD(TO_VARCHAR(F.SEQ_FRAME), 6, '0') || '.jpeg' 
		as FRAME_FILENAME
from SEQUENCE_FRAME F 
inner join SEQUENCE_CLIP C on C.SEQUENCE_CLIP_UUID = F.SEQUENCE_CLIP_UUID 