CREATE OR REPLACE PROCEDURE ADD_ANNOTATION_PACKAGE_DATA_CARD
(
	INOUT ANNOTATION_PACKAGE_UUID VARCHAR(36),
	IN ANNOTATION_SOURCE_MODELER VARCHAR(50), 
	IN ANALYSIS_TYPE VARCHAR(20),
	IN ANNOTATION_FILE_PATH      VARCHAR(400) --,
	-- OUT ANNOTATION_PACKAGE_UUID VARCHAR(36)
)
LANGUAGE SQLSCRIPT AS
BEGIN
	DECLARE ANNOTATION_PACKAGE_EXISTS INTEGER;
	DECLARE CURRENT_ANNOTATION_PACKAGE_UUID VARCHAR(36);

	select count(1) into ANNOTATION_PACKAGE_EXISTS
	from ANNOTATION_PACKAGE_DATA_CARD 
	where ANNOTATION_FILE_PATH = :ANNOTATION_FILE_PATH;
	
	if :ANNOTATION_PACKAGE_EXISTS = 0
	then

		insert into ANNOTATION_PACKAGE_DATA_CARD
		(
			ANNOTATION_PACKAGE_UUID,
			CLASSIFICATION,
			INSERTION_TIMESTAMP,
			ANNOTATION_FILE_PATH,
			ANNOTATION_SOURCE,
			ANALYSIS_TYPE
		)
		values
		(
			:ANNOTATION_PACKAGE_UUID,
			'Unclassified',
			CURRENT_TIMESTAMP,
			:ANNOTATION_FILE_PATH,
			:ANNOTATION_SOURCE_MODELER,
			:ANALYSIS_TYPE
		);
	else
		select ANNOTATION_PACKAGE_UUID into ANNOTATION_PACKAGE_UUID
		from ANNOTATION_PACKAGE_DATA_CARD 
		where ANNOTATION_FILE_PATH = :ANNOTATION_FILE_PATH;	
	end if;
	
	-- RETURN_ANNOTATION_PACKAGE_UUID = 
	--	select ANNOTATION_PACKAGE_UUID
	--	from ANNOTATION_PACKAGE_DATA_CARD 
	--	where ANNOTATION_FILE_PATH = :ANNOTATION_FILE_PATH;
		
END;
		