CREATE OR REPLACE PROCEDURE GET_SEQUENCE_CLIP_FRAMES_KEY_MAPPINGS
(
	IN  IN_SEQUENCE_CLIP_FILE_PATH        VARCHAR(200),
	OUT VIDEO_METADATA
		TABLE
		(
			SEQUENCE_CLIP_UUID VARCHAR(36),
			IMAGERY_PACKAGE_UUID VARCHAR(36),
			FPS DOUBLE,
			HEIGHT INTEGER,
			WIDTH INTEGER
		),
	OUT FRAME_KEY_MAPPINGS	
		TABLE 
		(
			SEQ_FRAME INTEGER,
			SEQUENCE_FRAME_UUID VARCHAR(36)
		)
)
LANGUAGE SQLSCRIPT AS
BEGIN


	VIDEO_METADATA =
		select 
			C.SEQUENCE_CLIP_UUID, 
			V.IMAGERY_PACKAGE_UUID, 
			V.FPS, 
			V.HEIGHT, 
			V.WIDTH
		from VIDEO V
		inner join SEQUENCE_CLIP C 
			on C.IMAGERY_PACKAGE_UUID = V.IMAGERY_PACKAGE_UUID
		where C.SEQUENCE_CLIP_FILE_PATH = :IN_SEQUENCE_CLIP_FILE_PATH;
		
	FRAME_KEY_MAPPINGS = 
		select 
			F.SEQ_FRAME,
			F.SEQUENCE_FRAME_UUID
		from SEQUENCE_FRAME F
		inner join SEQUENCE_CLIP C 
			on C.SEQUENCE_CLIP_UUID = F.SEQUENCE_CLIP_UUID
		where C.SEQUENCE_CLIP_FILE_PATH = :IN_SEQUENCE_CLIP_FILE_PATH;

END