CREATE OR REPLACE PROCEDURE GET_NEW_ANNOTATION_REQUESTS
(
	OUT ANNOTATION_REQUESTS TABLE
			(
				ANNOTATION_PACKAGE_UUID VARCHAR(36),
				IMAGERY_PACKAGE_UUID 	VARCHAR(36),
				SEQUENCE_CLIP_UUID 		VARCHAR(36),
				SEQ_FRAME	 			INTEGER,
				ANNOTATION_SOURCE 		VARCHAR(50),
				ANALYSIS_TYPE 			VARCHAR(20),
				IMAGERY_FILE_TYPE       VARCHAR(20),
				IMAGERY_FILE_PATH VARCHAR(200)
			)
)
LANGUAGE SQLSCRIPT AS
BEGIN

	ANNOTATION_REQUESTS =
		select 
			ANNOTATION_PACKAGE_UUID,
			IMAGERY_PACKAGE_UUID,
			SEQUENCE_CLIP_UUID,
			SEQ_FRAME,
			ANNOTATION_SOURCE,
			ANALYSIS_TYPE,
			'VIDEO' as IMAGERY_FILE_TYPE,
			IMAGERY_FILE_PATH
		from 
		(	select 
				R.*,
				'VIDEO' as IMAGERY_FILE_TYPE,
				C.SEQUENCE_CLIP_FILE_PATH as IMAGERY_FILE_PATH
			from ANNOTATION_REQUEST R
			inner join SEQUENCE_CLIP C on C.SEQUENCE_CLIP_UUID = R.SEQUENCE_CLIP_UUID
			where R.STATUS = 'NEW' and 
			R.SEQ_FRAME is null
			UNION
			select 
				R.*,
				'IMAGE' as IMAGERY_FILE_TYPE,
				F.FRAME_IMAGE_FILE_PATH as IMAGERY_FILE_PATH
			from ANNOTATION_REQUEST R
			inner join SEQUENCE_FRAME F 
				on F.SEQUENCE_CLIP_UUID = R.SEQUENCE_CLIP_UUID
				and F.SEQ_FRAME = R.SEQ_FRAME
			where R.STATUS = 'NEW' and 
			R.SEQ_FRAME is not null
		)
		order by INSERTION_TIMESTAMP;

END