CREATE OR REPLACE PROCEDURE  GET_IMAGERY_PACKAGE_METADATA_FOR_FMV_ANNOTATION
(
	IN IN_CLIP_FILENAME VARCHAR(200),
	OUT RESULT_TABLE		
	TABLE 
		(
			IMAGERY_PACKAGE_UUID VARCHAR(40),
			SEQUENCE_CLIP_UUID VARCHAR(36),
			SEQUENCE_CLIP_FILENAME VARCHAR(300),
			SEQUENCE_FRAME_UUID VARCHAR(36),
			SEQ_FRAME INTEGER
		)
)
LANGUAGE SQLSCRIPT AS
BEGIN

	DECLARE IMAGERY_PACKAGE_UUID VARCHAR(40);
	
	select IMAGERY_PACKAGE_UUID 
	into IMAGERY_PACKAGE_UUID
	from SEQUENCE_CLIP_VIEW
	where SEQUENCE_CLIP_FILENAME = :IN_CLIP_FILENAME;

	-- Given an input clip filename retrieve identifier information
	-- for all clips and frames that are part of the same imagery 
	-- package as the clip 	
	RESULT_TABLE =
		select 
			F.IMAGERY_PACKAGE_UUID, 
			F.SEQUENCE_CLIP_UUID,
			CV.SEQUENCE_CLIP_FILENAME,
			F.SEQUENCE_FRAME_UUID,
			F.SEQ_FRAME
		from SEQUENCE_FRAME F 
		inner join SEQUENCE_CLIP_VIEW CV 
			on CV.SEQUENCE_CLIP_UUID = F.SEQUENCE_CLIP_UUID
		where F.IMAGERY_PACKAGE_UUID = :IMAGERY_PACKAGE_UUID
		order by F.SEQUENCE_CLIP_UUID, F.SEQ_FRAME;

END