CREATE OR REPLACE PROCEDURE GET_FMV_ANNOTATION_PACKAGE_DATA_CARD_INFO
(
	IN IN_ANNOTATION_PACKAGE_UUID VARCHAR(36),
	OUT ANNOTATION_DATA_CARD_METADATA TABLE
		(
			ANNOTATION_PACKAGE_UUID VARCHAR(36),
			CLASSIFICATION VARCHAR(20),
			INSERTION_TIMESTAMP TIMESTAMP,
			ANNOTATION_FILE_PATH VARCHAR(400),
			ANNOTATION_SOURCE VARCHAR(50),
			ANNOTATION_COUNT BIGINT,
			OBJECT_COUNT BIGINT
		),
	OUT ANNOTATION_PACKAGE_LABEL_TYPE_STATS TABLE
		(
			LABEL_NAME VARCHAR(100),
			LABEL_ANNOTATION_COUNT BIGINT,
			LABEL_OBJECT_COUNT BIGINT
		),
	OUT ANNOTATION_IMAGERY_PACKAGES TABLE
		(
			IMAGERY_PACKAGE_UUID VARCHAR(40),
			CLASSIFICATION VARCHAR(20),
			IMAGERY_PACKAGE_TYPE VARCHAR(20),
			IMAGERY_PACKAGE_NAME VARCHAR(100),
			IMAGERY_PACKAGE_DESCRIPTION VARCHAR(1000),
			INSERTION_TIMESTAMP TIMESTAMP,
			TE_DESIGNATION VARCHAR(20),
			IMAGERY_START_TIME_STAMP TIMESTAMP,
			IMAGERY_END_TIME_STAMP TIMESTAMP,
			DURATION_SECONDS DOUBLE,
			FIRST_FRAME_FILEPATH VARCHAR(800),
			CLIP_COUNT BIGINT,
			FRAME_COUNT BIGINT,
			IMAGERY_PACKAGE_GEO_AREA_WKT CLOB
		),
	OUT ANNOTATION_PACKAGE_LABEL_TYPE_STATS_BY_IMAGERY_PACKAGE TABLE
		(
			IMAGERY_PACKAGE_UUID VARCHAR(40),
			LABEL_NAME VARCHAR(100),
			LABEL_ANNOTATION_COUNT BIGINT,
			LABEL_OBJECT_COUNT BIGINT,
			MIN_WIDTH_PIXELS INTEGER,
			MAX_WIDTH_PIXELS INTEGER,
			AVG_WIDTH_PIXELS DECIMAL,
			MIN_HEIGHT_PIXELS INTEGER,
			MAX_HEIGHT_PIXELS INTEGER,
			AVG_HEIGHT_PIXELS DECIMAL,
			MIN_AREA_PIXELS INTEGER,
			MAX_AREA_PIXELS INTEGER,
			AVG_AREA_PIXELS DECIMAL
		)
)
LANGUAGE SQLSCRIPT AS
BEGIN
	
	ANNOTATION_DATA_CARD_METADATA =
		select 
			C.ANNOTATION_PACKAGE_UUID,
			C.CLASSIFICATION,
			C.INSERTION_TIMESTAMP,
			C.ANNOTATION_FILE_PATH,
			C.ANNOTATION_SOURCE,
			count(1) as ANNOTATION_COUNT,
			count(distinct A.OBJECT_ID) as OBJECT_COUNT
		from ANNOTATION_PACKAGE_DATA_CARD C
		inner join SEQUENCE_FRAME_TRACK_ANNOTATION A
			on A.ANNOTATION_PACKAGE_UUID = C.ANNOTATION_PACKAGE_UUID
		where A.ANNOTATION_PACKAGE_UUID = :IN_ANNOTATION_PACKAGE_UUID
		group by
			C.ANNOTATION_PACKAGE_UUID,
			C.CLASSIFICATION,
			C.INSERTION_TIMESTAMP,
			C.ANNOTATION_FILE_PATH,
			C.ANNOTATION_SOURCE;
	
	ANNOTATION_PACKAGE_LABEL_TYPE_STATS =
		select 
		LABEL_NAME, 
		count(1) as LABEL_ANNOTATION_COUNT,
		count(distinct OBJECT_ID) LABEL_OBJECT_COUNT
		from SEQUENCE_FRAME_TRACK_ANNOTATION
		where ANNOTATION_PACKAGE_UUID = :IN_ANNOTATION_PACKAGE_UUID
		group by 
			LABEL_NAME;

	IMAGERY_PACKAGE_GEO_AREAS = 
		select 
			IMAGERY_PACKAGE_UUID, 
			ST_ConvexHullAggr(FRAME_CENTER_GEO_POINT).ST_AsWKT() as IMAGERY_PACKAGE_GEO_AREA_WKT
		from SEQUENCE_FRAME 
		where IMAGERY_PACKAGE_UUID in
			(select distinct IMAGERY_PACKAGE_UUID
			 from SEQUENCE_FRAME_TRACK_ANNOTATION
			 where ANNOTATION_PACKAGE_UUID = :IN_ANNOTATION_PACKAGE_UUID)
	group by IMAGERY_PACKAGE_UUID;
	
	ANNOTATION_IMAGERY_PACKAGES =
		select 
			V.*, 
			I.IMAGERY_PACKAGE_GEO_AREA_WKT
		from IMAGERY_PACKAGE_SUMMARY_VIEW V
		inner join :IMAGERY_PACKAGE_GEO_AREAS I 
			on I.IMAGERY_PACKAGE_UUID = V.IMAGERY_PACKAGE_UUID
		where V.IMAGERY_PACKAGE_UUID in 
			( select distinct IMAGERY_PACKAGE_UUID 
			  from SEQUENCE_FRAME_TRACK_ANNOTATION
			  where ANNOTATION_PACKAGE_UUID = :IN_ANNOTATION_PACKAGE_UUID);
		

	ANNOTATION_PACKAGE_LABEL_TYPE_STATS_BY_IMAGERY_PACKAGE =
		select distinct
			IMAGERY_PACKAGE_UUID,
			LABEL_NAME, 
			count(1) as LABEL_ANNOTATION_COUNT,
			count(distinct OBJECT_ID) LABEL_OBJECT_COUNT,
			min(WIDTH_PIXELS) as MIN_WIDTH_PIXELS,
			max(WIDTH_PIXELS) as MAX_WIDTH_PIXELS,
			avg(WIDTH_PIXELS) as AVG_WIDTH_PIXELS,
			min(HEIGHT_PIXELS) as MIN_HEIGHT_PIXELS,
			max(HEIGHT_PIXELS) as MAX_HEIGHT_PIXELS,
			avg(HEIGHT_PIXELS) as AVG_HEIGHT_PIXELS,
			min(AREA_PIXELS) as MIN_AREA_PIXELS,
			max(AREA_PIXELS) as MAX_AREA_PIXELS,
			avg(AREA_PIXELS) as AVG_AREA_PIXELS
		from SEQUENCE_FRAME_TRACK_ANNOTATION
		where ANNOTATION_PACKAGE_UUID = :IN_ANNOTATION_PACKAGE_UUID
		group by 
			IMAGERY_PACKAGE_UUID,
			LABEL_NAME;

END