CREATE OR REPLACE PROCEDURE GET_ANNOTATIONS_FOR_SEQUENCE_FRAME
(
	IN  IN_SEQUENCE_FRAME_UUID VARCHAR(36),
	IN  IN_ANNOTATION_SOURCE VARCHAR(50),
	IN  IN_ANALYSIS_TYPE VARCHAR(20),
	IN  MINIMUM_CONFIDENCE INTEGER DEFAULT 0,
	OUT ANNOTATIONS	
		TABLE 
		(
			ANNOTATION_UUID       VARCHAR(36),
			OBJECT_NAME           VARCHAR(100),
			LABEL_NAME            VARCHAR(100),
			ANNOTATION_AS_GEOJSON CLOB,
			ANNO_ATTRIBUTES       NVARCHAR(5000),
			CONFIDENCE            INTEGER
		) DEFAULT EMPTY,
	OUT LABELS
		TABLE 
		(
			ANNOTATION_UUID VARCHAR(36),
			LABEL           VARCHAR(100),
			CONFIDENCE      INTEGER
		) DEFAULT EMPTY
)
LANGUAGE SQLSCRIPT AS
BEGIN


	if :IN_ANALYSIS_TYPE = 'faces'
	then

		ANNOTATIONS = 
			select 
				A.ANNOTATION_UUID,
				A.OBJECT_NAME,
				A.LABEL_NAME,
				A.ANNOTATION_GEO_POLYGON.St_AsGeoJSON() as ANNOTATION_AS_GEOJSON,
				Null as ANNO_ATTRIBUTES,
				A.CONFIDENCE
			from SEQUENCE_FRAME_FACE_ANNOTATION A
			inner join ANNOTATION_PACKAGE_DATA_CARD C 
			 on C.ANNOTATION_PACKAGE_UUID = A.ANNOTATION_PACKAGE_UUID
			where A.SEQUENCE_FRAME_UUID = :IN_SEQUENCE_FRAME_UUID
			and A.CONFIDENCE >= :MINIMUM_CONFIDENCE
			and C.ANNOTATION_SOURCE = :IN_ANNOTATION_SOURCE
			and C.ANALYSIS_TYPE = :IN_ANALYSIS_TYPE;
			
		ANNOTATIONS = 
			select 
				A.ANNOTATION_UUID,
				A.OBJECT_NAME,
				A.LABEL_NAME,
				A.ANNOTATION_AS_GEOJSON,
				ATTR.ATTRIBUTES as ANNO_ATTRIBUTES,
				A.CONFIDENCE
			from :ANNOTATIONS A
			left outer join 
			(
				select ATTR.ANNOTATION_UUID,
				STRING_AGG(FACE_ATTRIBUTE_VALUE, 
				           ', ' ORDER BY FACE_ATTRIBUTE_VALUE) AS ATTRIBUTES
				from SEQUENCE_FRAME_FACE_ANNOTATION_ATTRIBUTE ATTR
				inner join :ANNOTATIONS A 
					on A.ANNOTATION_UUID = ATTR.ANNOTATION_UUID
				where ATTR.CONFIDENCE >= :MINIMUM_CONFIDENCE
				group by ATTR.ANNOTATION_UUID 
			) ATTR on ATTR.ANNOTATION_UUID = A.ANNOTATION_UUID; 

	end if;
	
	if :IN_ANALYSIS_TYPE = 'text'
	then

		ANNOTATIONS = 
			select 
				A.ANNOTATION_UUID,
				A.OBJECT_NAME,
				A.LABEL_NAME,
				A.ANNOTATION_GEO_POLYGON.St_AsGeoJSON() as ANNOTATION_AS_GEOJSON,
				A.DETECTED_TEXT as ANNO_ATTRIBUTES,
				A.CONFIDENCE
			from SEQUENCE_FRAME_TEXT_ANNOTATION A
			inner join ANNOTATION_PACKAGE_DATA_CARD C 
				on C.ANNOTATION_PACKAGE_UUID = A.ANNOTATION_PACKAGE_UUID
			where A.SEQUENCE_FRAME_UUID = :IN_SEQUENCE_FRAME_UUID
		    and A.CONFIDENCE >= :MINIMUM_CONFIDENCE
			and C.ANNOTATION_SOURCE = :IN_ANNOTATION_SOURCE
			and C.ANALYSIS_TYPE = :IN_ANALYSIS_TYPE;
	
	end if;

	if :IN_ANALYSIS_TYPE = 'labels'
	then

		ANNOTATIONS = 
			select 
				A.ANNOTATION_UUID,
				A.OBJECT_NAME,
				A.LABEL_NAME,
				A.ANNOTATION_GEO_POLYGON.St_AsGeoJSON() as ANNOTATION_AS_GEOJSON,
				Null as ANNO_ATTRIBUTES,
				A.CONFIDENCE
			from SEQUENCE_FRAME_TRACK_ANNOTATION A
			inner join ANNOTATION_PACKAGE_DATA_CARD C 
				on C.ANNOTATION_PACKAGE_UUID = A.ANNOTATION_PACKAGE_UUID
			where A.SEQUENCE_FRAME_UUID = :IN_SEQUENCE_FRAME_UUID
		    and A.CONFIDENCE >= :MINIMUM_CONFIDENCE
			and C.ANNOTATION_SOURCE = :IN_ANNOTATION_SOURCE
			and C.ANALYSIS_TYPE = :IN_ANALYSIS_TYPE;
	

		LABELS = 
			select 
				L.ANNOTATION_UUID,
				L.LABEL,
				L.CONFIDENCE
			from SEQUENCE_CLIP_FRAME_LABEL L
			inner join ANNOTATION_PACKAGE_DATA_CARD C 
				on C.ANNOTATION_PACKAGE_UUID = L.ANNOTATION_PACKAGE_UUID
			inner join SEQUENCE_FRAME F 
				on F.SEQUENCE_CLIP_UUID = L.SEQUENCE_CLIP_UUID and 
                   F.SEQ_FRAME = L.SEQ_FRAME				
			where F.SEQUENCE_FRAME_UUID = :IN_SEQUENCE_FRAME_UUID
			and L.CONFIDENCE >= :MINIMUM_CONFIDENCE
			and C.ANNOTATION_SOURCE = :IN_ANNOTATION_SOURCE
			and C.ANALYSIS_TYPE = :IN_ANALYSIS_TYPE;

	end if;

END