CREATE OR REPLACE PROCEDURE GET_FMV_ANNOTATIONS
(
	IN  IN_IMAGERY_PACKAGE_UUID        VARCHAR(40),
	IN  IN_ANNOTATION_PACKAGE_UUID     VARCHAR(40),
	OUT FRAME_ANNOTATIONS	
		TABLE 
		(
			SEQUENCE_FRAME_UUID VARCHAR(36),
			SEQUENCE_CLIP_FILENAME VARCHAR(200),
			SEQ_FRAME INTEGER,
			CLIP_NAME VARCHAR(200),
			SEQUENCE_CLIP_FILE_PATH VARCHAR(400),
			FRAME_FILENAME VARCHAR(300),
			FRAME_IMAGE_FILE_PATH VARCHAR(400),
			ANNOTATION_ID VARCHAR(40),
			OBJECT_NAME VARCHAR(100),
			ANNOTATION_TYPE VARCHAR(20),
			COORDS VARCHAR(400),
			LABEL_NAME VARCHAR(100)
		)
)
LANGUAGE SQLSCRIPT AS
BEGIN

	FRAME_ANNOTATIONS = 
		select 
			A.SEQUENCE_FRAME_UUID,
			A.SEQUENCE_CLIP_FILENAME,
			A.SEQ_FRAME,
			CV.CLIP_NAME,
			CV.SEQUENCE_CLIP_FILE_PATH,
			FV.FRAME_FILENAME,
			FV.FRAME_IMAGE_FILE_PATH,
			A.ANNOTATION_ID,
			A.OBJECT_NAME,
			A.ANNOTATION_TYPE,
			A.COORDS,
			A.LABEL_NAME
		from IMAGERY_PACKAGE_DATA_CARD I
		inner join SEQUENCE_CLIP_VIEW CV on I.IMAGERY_PACKAGE_UUID = CV.IMAGERY_PACKAGE_UUID
		inner join SEQUENCE_FRAME_VIEW FV on FV.SEQUENCE_CLIP_UUID = CV.SEQUENCE_CLIP_UUID
		inner join SEQUENCE_FRAME_TRACK_ANNOTATION A 
			on A.SEQUENCE_FRAME_UUID = FV.SEQUENCE_FRAME_UUID
		where I.IMAGERY_PACKAGE_UUID = :IN_IMAGERY_PACKAGE_UUID
		and A.ANNOTATION_PACKAGE_UUID = :IN_ANNOTATION_PACKAGE_UUID
		order by A.SEQUENCE_CLIP_FILENAME, A.SEQ_FRAME;
	
END;