CREATE OR REPLACE PROCEDURE GET_SEQUENCE_CLIP_INFO
(
	IN IN_CLIP_FILENAME VARCHAR(200),
	OUT SEQUENCE_CLIP_METADATA TABLE
		(
			IMAGERY_PACKAGE_UUID VARCHAR(36),
			SEQUENCE_CLIP_UUID VARCHAR(36),
			CLASSIFICATION VARCHAR(20),
			SEQUENCE_CLIP_FILENAME VARCHAR(300),
			START_TIMESTAMP TIMESTAMP,
			END_TIMESTAMP TIMESTAMP,
			FRAME_COUNT BIGINT
		),
	OUT FRAME_CENTER_TRACK TABLE
		(
			SEQ_FRAME INTEGER,
			FRAME_CENTER_LON DOUBLE,
			FRAME_CENTER_LAT DOUBLE
		),
	OUT SENSOR_TRACK TABLE
		(
			SEQ_FRAME INTEGER,
			SENSOR_LON DOUBLE,
			SENSOR_LAT DOUBLE
		),
	OUT ANNOTATION_PACKAGES TABLE
		(
			ANNOTATION_PACKAGE_UUID VARCHAR(36),
			CLASSIFICATION VARCHAR(20),
			INSERTION_TIMESTAMP TIMESTAMP,
			ANNOTATION_FILE_PATH VARCHAR(400),
			ANNOTATION_SOURCE VARCHAR(50),
			ANNOTATION_COUNT BIGINT,
			OBJECT_COUNT BIGINT
		),
	OUT ANNOTATION_PACKAGE_LABEL_TYPE_STATS TABLE
		(
			ANNOTATION_PACKAGE_UUID VARCHAR(36),
			LABEL_NAME VARCHAR(100),
			LABEL_ANNOTATION_COUNT BIGINT,
			LABEL_OBJECT_COUNT BIGINT
		),
	OUT SENSOR_INFO TABLE
		(
			IMAGERY_PACKAGE_UUID VARCHAR(36),
			MISSION_ID VARCHAR(50), 
			TAIL_NUMBER VARCHAR(100), 
			PLATFORM_TYPE VARCHAR(100),
			MIN_SENSOR_TRUE_ALTITUDE DOUBLE,
			MAX_SENSOR_TRUE_ALTITUDE DOUBLE,		
			MIN_SENSOR_RELATIVE_PITCH_ANGLE DOUBLE,
			MAX_SENSOR_RELATIVE_PITCH_ANGLE DOUBLE,
			MIN_SENSOR_RELATIVE_ROLL_ANGLE DOUBLE,
			MAX_SENSOR_RELATIVE_ROLL_ANGLE DOUBLE,
			MIN_PLATFORM_GROUND_SPEED DOUBLE, 
			MAX_PLATFORM_GROUND_SPEED DOUBLE,
			MIN_PLATFORM_HEADING DOUBLE, 
			MAX_PLATFORM_HEADING DOUBLE,
			MIN_PLATFORM_TRUE_AIRSPEED DOUBLE,
			MAX_PLATFORM_TRUE_AIRSPEED DOUBLE,		
			MIN_PLATFORM_PITCH_ANGLE DOUBLE,
			MAX_PLATFORM_PITCH_ANGLE DOUBLE,
			IMAGE_SOURCE_SENSOR VARCHAR(5000)
		)
)
LANGUAGE SQLSCRIPT AS
BEGIN
	DECLARE THIS_SEQUENCE_CLIP_UUID VARCHAR(36);

	select SEQUENCE_CLIP_UUID into THIS_SEQUENCE_CLIP_UUID
	from SEQUENCE_CLIP_VIEW 
	where SEQUENCE_CLIP_FILENAME = :IN_CLIP_FILENAME;
	
	SEQUENCE_CLIP_METADATA = 
		select
			IMAGERY_PACKAGE_UUID,
			SEQUENCE_CLIP_UUID,
			CLASSIFICATION,
			SEQUENCE_CLIP_FILENAME,
			START_TIMESTAMP,
			END_TIMESTAMP,
			FRAME_COUNT
		from
		(
			select
				CV.IMAGERY_PACKAGE_UUID,
				CV.SEQUENCE_CLIP_UUID,
				CV.CLASSIFICATION,
				CV.SEQUENCE_CLIP_FILENAME,
				CV.START_TIMESTAMP,
				CV.END_TIMESTAMP
			from SEQUENCE_CLIP_VIEW CV
			where CV.SEQUENCE_CLIP_UUID = :THIS_SEQUENCE_CLIP_UUID
		),
		(
			select count(1) as FRAME_COUNT
			from SEQUENCE_FRAME 
			where SEQUENCE_CLIP_UUID = :THIS_SEQUENCE_CLIP_UUID
		);
	
	-- TRACK OF CENTER POINT OF FRAMES
	FRAME_CENTER_TRACK =
		select 
			SEQ_FRAME,
			FRAME_CENTER_LON, 
			FRAME_CENTER_LAT
		from SEQUENCE_FRAME
		where SEQUENCE_CLIP_UUID = :THIS_SEQUENCE_CLIP_UUID
		and ( SEQ_FRAME = 1
		      OR
			  SEQ_FRAME in (select max(SEQ_FRAME)
			                from SEQUENCE_FRAME 
							where SEQUENCE_CLIP_UUID = :THIS_SEQUENCE_CLIP_UUID
			               )
            )		
		order by SEQ_FRAME;
		
	-- TRACK OF SENSOR PLATFORM LOCATION
	SENSOR_TRACK =
		select 
			SEQ_FRAME,
			SENSOR_LON, 
			SENSOR_LAT
		from SEQUENCE_FRAME
		where SEQUENCE_CLIP_UUID = :THIS_SEQUENCE_CLIP_UUID
		and ( SEQ_FRAME = 1
		      OR
			  SEQ_FRAME in (select max(SEQ_FRAME)
			                from SEQUENCE_FRAME 
							where SEQUENCE_CLIP_UUID = :THIS_SEQUENCE_CLIP_UUID
			               )
            )	
		order by SEQ_FRAME;	
	-- ANNOTATION_PACKAGES INCLUDING # OF SEQUENCE_CLIPS AND 
	-- SEQUENCE_FRAMES WITH ANNOTATIONS
	ANNOTATION_PACKAGES =
		select distinct 
			C.ANNOTATION_PACKAGE_UUID,
			C.CLASSIFICATION,
			C.INSERTION_TIMESTAMP,
			C.ANNOTATION_FILE_PATH,
			C.ANNOTATION_SOURCE,
			count(1) as ANNOTATION_COUNT,
			count(distinct A.OBJECT_ID) as OBJECT_COUNT
		from ANNOTATION_PACKAGE_DATA_CARD C
		inner join SEQUENCE_FRAME_TRACK_ANNOTATION A
			on A.ANNOTATION_PACKAGE_UUID = C.ANNOTATION_PACKAGE_UUID
		where A.SEQUENCE_CLIP_FILENAME = :IN_CLIP_FILENAME
		group by 
			C.ANNOTATION_PACKAGE_UUID,
			C.CLASSIFICATION,
			C.INSERTION_TIMESTAMP,
			C.ANNOTATION_FILE_PATH,
			C.ANNOTATION_SOURCE;
	
	-- FOR EACH ANNOTATION PACKAGE NUMBER OF OBJECTS OF EACH LABEL TYPE
	-- AND NUMBER OF OCCURANCES OF EACH TYPE
	ANNOTATION_PACKAGE_LABEL_TYPE_STATS =
		select distinct
		ANNOTATION_PACKAGE_UUID,
		LABEL_NAME, 
		count(1) as LABEL_ANNOTATION_COUNT,
		count(distinct OBJECT_ID) LABEL_OBJECT_COUNT
		from SEQUENCE_FRAME_TRACK_ANNOTATION
		where SEQUENCE_CLIP_FILENAME = :IN_CLIP_FILENAME
		group by 
			ANNOTATION_PACKAGE_UUID,
			LABEL_NAME;
			
	SENSOR_INFO = 
		select distinct 
			F.*,
			A.IMAGE_SOURCE_SENSOR 
		from 
		(
			select distinct
				IMAGERY_PACKAGE_UUID,
				MISSION_ID, 
				TAIL_NUMBER, 
				PLATFORM_TYPE,
				min(SENSOR_TRUE_ALTITUDE) as MIN_SENSOR_TRUE_ALTITUDE,
				max(SENSOR_TRUE_ALTITUDE) as MAX_SENSOR_TRUE_ALTITUDE,		
				min(SENSOR_RELATIVE_PITCH_ANGLE) as MIN_SENSOR_RELATIVE_PITCH_ANGLE,
				max(SENSOR_RELATIVE_PITCH_ANGLE) as MAX_SENSOR_RELATIVE_PITCH_ANGLE,
				min(SENSOR_RELATIVE_ROLL_ANGLE) as MIN_SENSOR_RELATIVE_ROLL_ANGLE,
				max(SENSOR_RELATIVE_ROLL_ANGLE) as MAX_SENSOR_RELATIVE_ROLL_ANGLE,
				min(PLATFORM_GROUND_SPEED) as MIN_PLATFORM_GROUND_SPEED, 
				max(PLATFORM_GROUND_SPEED) as MAX_PLATFORM_GROUND_SPEED,
				min(PLATFORM_HEADING) as MIN_PLATFORM_HEADING, 
				max(PLATFORM_HEADING) as MAX_PLATFORM_HEADING,
				min(PLATFORM_TRUE_AIRSPEED) as MIN_PLATFORM_TRUE_AIRSPEED,
				max(PLATFORM_TRUE_AIRSPEED) as MAX_PLATFORM_TRUE_AIRSPEED,		
				min(PLATFORM_PITCH_ANGLE) as MIN_PLATFORM_PITCH_ANGLE,
				max(PLATFORM_PITCH_ANGLE) as MAX_PLATFORM_PITCH_ANGLE		
			from SEQUENCE_FRAME
			where SEQUENCE_CLIP_UUID = :THIS_SEQUENCE_CLIP_UUID
			group by
				IMAGERY_PACKAGE_UUID,
				MISSION_ID, 
				TAIL_NUMBER, 
				PLATFORM_TYPE			
		) as F,
		(
			select
				IMAGERY_PACKAGE_UUID,
				STRING_AGG(IMAGE_SOURCE_SENSOR, ', ' order by IMAGE_SOURCE_SENSOR)
				as IMAGE_SOURCE_SENSOR 
			from
			(
				select distinct 
					IMAGERY_PACKAGE_UUID,
					IMAGE_SOURCE_SENSOR
				from SEQUENCE_FRAME
				where SEQUENCE_CLIP_UUID = :THIS_SEQUENCE_CLIP_UUID
			)
			group by IMAGERY_PACKAGE_UUID
		) as A;

END