CREATE PROCEDURE GET_FRAMES_HEAT_MAP
(
	OUT SEQUENCE_FRAMES_HEATMAP TABLE
	(
		CLUSTER_CENTER_POINT_WKT VARCHAR(50),
		LON DOUBLE,
		LAT DOUBLE,
		COUNTER BIGINT
	) 
)
LANGUAGE SQLSCRIPT AS
BEGIN	
	SEQUENCE_FRAMES_HEATMAP =
		select 
			CAST(ST_ClusterCentroid().ST_ASWKT() as VARCHAR(50)) 
				AS CLUSTER_CENTER_POINT_WKT,
			ST_ClusterCentroid().ST_X() as LON, 
			ST_ClusterCentroid().ST_Y() as LAT, 
			count(1) as COUNTER
		from SEQUENCE_FRAME
		where FRAME_CENTER_GEO_POINT is not null
		group cluster by FRAME_CENTER_GEO_POINT 
		using KMEANS CLUSTERS 1024;

END