CREATE OR REPLACE PROCEDURE SET_ANNOTATION_REQUEST_STATUS
(
	IN ANNOTATION_PACKAGE_UUID VARCHAR(36),
	IN STATUS VARCHAR(30),
	IN STATUS_MESSAGE VARCHAR(1000),
	IN ANNOTATION_FILE_PATH VARCHAR(200)
)
LANGUAGE SQLSCRIPT AS
BEGIN

	update ANNOTATION_REQUEST
	set 
		STATUS = :STATUS,
		STATUS_MESSAGE = :STATUS_MESSAGE,
		STATUS_TIMESTAMP = CURRENT_TIMESTAMP
	where ANNOTATION_PACKAGE_UUID = :ANNOTATION_PACKAGE_UUID;	

	if :ANNOTATION_FILE_PATH is not null
	then
	
		update ANNOTATION_REQUEST
			set 
				ANNOTATION_FILE_PATH = :ANNOTATION_FILE_PATH,
				STATUS_TIMESTAMP = CURRENT_TIMESTAMP
			where ANNOTATION_PACKAGE_UUID = :ANNOTATION_PACKAGE_UUID;	
	end if;
	
END